spring:
  application:
    name: taska

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/taskaDB
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
      open-in-view: false

  jwt:
    secret: ${JWT_SECRET}
    expiration: 432000000


springdoc:
  swagger-ui:
    path: /docs